### ISSUE TITLE
Requirements to integrate with SLACK?

### ISSUE THREAD

**Issue by shaggyos** [suda/slack-hangout#1]
Hi,
What was required to integrate this with slack?
Firstly, I am not sure I have the google oauth2 working properly.  I can use my url/auth and receive a token code, which I then use in my heroku application as one of the vars.  However, I'm receiving an "Invalid request" at the moment after adjusting the url to use o/auth2/token (instead of o/auth2/auth, which gave an incorrect response_type error).  I am trying to update the install document to reflect the changes in web presentation/menu's at each step to bring this up to date.

Thanks
Shauno

**Comment by suda** [comment]
@shaggyos actually I abandoned this project in favor of official slack Hangouts integration: https://slack.com/apps/A0F7YS351-google-hangouts
